### ISSUE TITLE
Create new MRA files for CPS1 games

### ISSUE THREAD

**Issue by jotego** [jotego/jtcores#153]
JTCPS1 was the first core to extract information from MAME in order to create the MRA files. Since then JTFRAME has advanced a long way to make this a standard step of core development. JTCPS1 MRA files are not well supported now as they are not covered by the new workflow and they have had merges in JTBIN.

**Missing MRA features**
- Button names
- _ccw_ annotations for vertical games

**Tasks**
- [x] Export the header section of current MRA files into a new _mame2mra.toml_ file
- [x] Add button names
- [x] Correct DIP switch names
- [ ] Add flow for custom MRA files
- [ ] Keep MRA files for DMA speed tests
- [x] Check that there are no extra spaces in between words in 1941 and Varth MRA file names (Old jotego/jtcps#149)
- [ ] Requires https://github.com/jotego/jtframe/issues/103
